### PR TITLE
Added seconds and none granularity

### PR DESCRIPTION
**Pull request by kvsurii**
Referencing #43 
screen shot 2017-12-03 at 8 13 20 pm

### CODE REVIEW

**Comment by pkarmaka** [comment]
I don't think none is really needed here. @abhisant ?

**Comment by gavinmcnair** [comment]
Should we not just have all the valid Druid granularities here? (all, none, second, minute, fifteen_minute, thirty_minute, hour, day, week, month, quarter and year)

http://druid.io/docs/latest/querying/granularities.html

**Comment by pkarmaka** [comment]
@kvsurii I am getting an error. Can you test this on your side please?

image

**Comment by kvsurii** [comment]
@pranit22 @pkarmaka will make changes for this and get back to you.

**Comment by pranit22** [comment]
@kvsurii just wanted to check if you managed to get this work, we can merge this PR when we have the complete set of granularities available.

**Comment by pranit22** [comment]
@kvsurii just checking again if you got a chance to get this fixed?

**Comment by pranit22** [comment]
#59 takes care of this.

**Pull request closed without merging**
